// Generated by tools/generate_ap_mappings.py. Do not edit by hand.

function mw_ap_item_names()
{
    static names = [
        "Charge Beam",
        "Wave Beam",
        "Ice Beam",
        "Plasma Beam",
        "Spazer",
        "Wavebuster",
        "Ice Spreader",
        "Incinerator",
        "Varia Suit",
        "Gravity Suit",
        "Phazon Suit",
        "Morph Ball",
        "Boost Ball",
        "Space Jump Boots",
        "Screw Attack",
        "Morph Ball Bomb",
        "Spider Ball",
        "Grapple Beam",
        "Super Missile",
        "Progressive Grapple Beam",
        "Artifact of Truth",
        "Artifact of Strength",
        "Artifact of Elder",
        "Artifact of Wild",
        "Artifact of Lifegiver",
        "Artifact of Chozo",
        "Artifact of Warrior",
        "Artifact of Nature",
        "Artifact of Sun",
        "Artifact of World",
        "Artifact of Spirit",
        "Artifact of Newborn",
        "Energy Tank",
        "Power Bomb",
        "Missile Tank"
    ];
    return names;
}

function mw_ap_item_name(item_id)
{
    var names = mw_ap_item_names();
    if (item_id < 1 || item_id > array_length(names))
    {
        return "";
    }
    return names[item_id - 1];
}

function mw_ap_location_keys()
{
    static keys = [
        "Artifact 4 cho_Sunchamber x320 y224",
        "Varia Suit cho_Sunchamber x56 y320",
        "Artifact 10 cho_Elder_Chamber x152 y72",
        "Energy Tanks Max cho_Hall_of_the_Elders x384 y32",
        "Morph Ball cho_Ruined_Shrine x672 y128",
        "Missiles Max cho_Ruined_Shrine x272 y32",
        "Missiles Max cho_Ruined_Shrine x904 y168",
        "Charge Beam cho_Watery_Hall x480 y104",
        "Missiles Max cho_Gathering_Hall x280 y24",
        "Missiles Max cho_Watery_Hall x560 y288",
        "Missiles Max cho_Watery_Hall_Access x151 y135",
        "Ice Beam cho_Antechamber x152 y176",
        "Artifact 5 cho_Tower_Chamber x160 y112",
        "Wavebuster cho_Tower_of_Light x151 y65",
        "Energy Tanks Max cho_Furnace_subC x160 y112",
        "Missiles Max cho_Furnace_subD x288 y32",
        "Morph Ball Bomb cho_Burn_Dome x152 y160",
        "Missiles Max cho_Burn_Dome_subB x208 y112",
        "Missiles Max cho_Crossway x16 y48",
        "Missiles Max cho_Dynamo x224 y32",
        "Missiles Max cho_Dynamo x272 y368",
        "Energy Tanks Max cho_Transport_Access_North x152 y134",
        "Missiles Max cho_Hive_Totem x152 y144",
        "Energy Tanks Max cho_Main_Plaza x104 y256",
        "Missiles Max cho_Main_Plaza x120 y520",
        "Missiles Max cho_Main_Plaza x584 y456",
        "Missiles Max cho_Main_Plaza x64 y80",
        "Missiles Max cho_Ruined_Gallery x48 y336",
        "Missiles Max cho_Ruined_Gallery x592 y248",
        "Missiles Max cho_Ruined_Nursery x352 y320",
        "Missiles Max cho_Ruined_Fountain x576 y160",
        "Energy Tanks Max cho_Training_Chamber x392 y72",
        "Missiles Max cho_Training_Chamber_Access x288 y144",
        "Power Bombs Max cho_Magma_Pool x584 y168",
        "Missiles Max cho_Vault x192 y112",
        "Artifact 2 mag_Warrior_Shrine x112 y64",
        "Ice Spreader mag_Shore_Tunnel x152 y148",
        "Energy Tanks Max mag_Transport_Tunnel_A x160 y48",
        "Power Bombs Max mag_Fiery_Shores x576 y32",
        "Missiles Max mag_Storage_Cavern x48 y80",
        "Missiles Max mag_Triclops_Pit x512 y64",
        "Artifact 8 mag_Lava_Lake_subC x274 y78",
        "Plasma Beam mag_Plasma_Processing x192 y128",
        "Energy Tanks Max mag_Magmoor_Workstation x568 y377",
        "Missiles Max mag_Fiery_Shores x48 y64",
        "Artifact 6 pha_Elite_Research x112 y96",
        "Missiles Max pha_Elite_Research_subB x128 y32",
        "Artifact 12 pha_Phazon_Mining_Tunnel x104 y347",
        "Incinerator pha_Storage_Depot_A x160 y120",
        "Missiles Max pha_Security_Access_A x192 y176",
        "Grapple Beam pha_Storage_Depot_B x208 y139",
        "Phazon Suit pha_Elite_Quarters x320 y352",
        "Energy Tanks Max pha_Processing_Center_Access x72 y120",
        "Energy Tanks Max pha_Ventilation_Shaft x152 y352",
        "Missiles Max pha_Elite_Control_Access x224 y48",
        "Missiles Max pha_Fungal_Hall_Access x208 y400",
        "Missiles Max pha_Fungal_Hall_B x912 y240",
        "Missiles Max pha_Main_Quarry x592 y48",
        "Missiles Max pha_Metroid_Quarantine_A x512 y48",
        "Missiles Max pha_Metroid_Quarantine_B x888 y304",
        "Missiles Max pha_Phazon_Processing_Center x568 y632",
        "Power Bombs Max pha_Central_Dynamo x312 y296",
        "Artifact 3 phe_Control_Tower_subC x240 y128",
        "Energy Tanks Max phe_Research_Lab_Aether_subB x169 y144",
        "Missiles Max phe_Research_Lab_Aether x352 y192",
        "Artifact 9 phe_Chozo_Ice_Temple_subD x168 y152",
        "Wave Beam phe_Chapel_of_the_Elders_subB x144 y136",
        "Artifact 11 phe_Storage_Cave x184 y120",
        "Spider Ball phe_Quarantine_Cave x320 y298.67",
        "Missiles Max phe_Quarantine_Monitor x184 y128",
        "Spazer phe_Research_Core x160 y552",
        "Gravity Suit phe_Gravity_Chamber x80 y96",
        "Missiles Max phe_Gravity_Chamber_subB x56 y32",
        "Super Missile phe_Observatory x304 y56",
        "Energy Tanks Max phe_Ruined_Courtyard x16 y400",
        "Energy Tanks Max phe_Transport_Access x160 y160",
        "Missiles Max phe_Frost_Cave x296 y392",
        "Boost Ball phe_Phendrana_Canyon_subB x144 y112",
        "Missiles Max phe_Ice_Ruins_East x16 y32",
        "Missiles Max phe_Ice_Ruins_East x368 y256",
        "Missiles Max phe_Phendrana_Shorelines_subB x112 y832",
        "Missiles Max phe_Phendrana_Shorelines_subB x544 y256",
        "Power Bombs Max phe_Ice_Ruins_West x360 y248",
        "Missiles Max phe_Research_Lab_Hydra_subB x376 y160",
        "Power Bombs Max phe_Security_Cave x168 y120",
        "Artifact 1 tal_Cipher_Site x288 y371",
        "Artifact 7 tal_Life_Grove x488 y320",
        "Screw Attack tal_Life_Grove x72 y344",
        "Missiles Max tal_Life_Grove_Tunnel x304 y96",
        "Energy Tanks Max tal_Cargo_Freight_Lift_to_Deck_Gamma x233 y124",
        "Energy Tanks Max tal_Hydro_Access_Tunnel x576 y144",
        "Missiles Max tal_Biohazard_Containment x265 y384",
        "Missiles Max tal_Arbor_Chamber x144 y80",
        "Missiles Max tal_Root_Cave x48 y208",
        "Missiles Max tal_Transport_Tunnel_B x152 y160",
        "Missiles Max tal_Crash_Site x616 y296",
        "Missiles Max tal_Great_Tree_Chamber x152 y136",
        "Space Jump Boots tal_Alcove x224 y128",
        "Missiles Max tal_Landing_Site x800 y528",
        "Missiles Max tal_Overgrown_Cavern x144 y128"
    ];
    return keys;
}

function mw_ap_location_key(location_id)
{
    var keys = mw_ap_location_keys();
    if (location_id < 1 || location_id > array_length(keys))
    {
        return "";
    }
    return keys[location_id - 1];
}

function mw_ap_location_id(location_key)
{
    switch (location_key)
    {
        case "Artifact 4 cho_Sunchamber x320 y224": return 1;
        case "Varia Suit cho_Sunchamber x56 y320": return 2;
        case "Artifact 10 cho_Elder_Chamber x152 y72": return 3;
        case "Energy Tanks Max cho_Hall_of_the_Elders x384 y32": return 4;
        case "Morph Ball cho_Ruined_Shrine x672 y128": return 5;
        case "Missiles Max cho_Ruined_Shrine x272 y32": return 6;
        case "Missiles Max cho_Ruined_Shrine x904 y168": return 7;
        case "Charge Beam cho_Watery_Hall x480 y104": return 8;
        case "Missiles Max cho_Gathering_Hall x280 y24": return 9;
        case "Missiles Max cho_Watery_Hall x560 y288": return 10;
        case "Missiles Max cho_Watery_Hall_Access x151 y135": return 11;
        case "Ice Beam cho_Antechamber x152 y176": return 12;
        case "Artifact 5 cho_Tower_Chamber x160 y112": return 13;
        case "Wavebuster cho_Tower_of_Light x151 y65": return 14;
        case "Energy Tanks Max cho_Furnace_subC x160 y112": return 15;
        case "Missiles Max cho_Furnace_subD x288 y32": return 16;
        case "Morph Ball Bomb cho_Burn_Dome x152 y160": return 17;
        case "Missiles Max cho_Burn_Dome_subB x208 y112": return 18;
        case "Missiles Max cho_Crossway x16 y48": return 19;
        case "Missiles Max cho_Dynamo x224 y32": return 20;
        case "Missiles Max cho_Dynamo x272 y368": return 21;
        case "Energy Tanks Max cho_Transport_Access_North x152 y134": return 22;
        case "Missiles Max cho_Hive_Totem x152 y144": return 23;
        case "Energy Tanks Max cho_Main_Plaza x104 y256": return 24;
        case "Missiles Max cho_Main_Plaza x120 y520": return 25;
        case "Missiles Max cho_Main_Plaza x584 y456": return 26;
        case "Missiles Max cho_Main_Plaza x64 y80": return 27;
        case "Missiles Max cho_Ruined_Gallery x48 y336": return 28;
        case "Missiles Max cho_Ruined_Gallery x592 y248": return 29;
        case "Missiles Max cho_Ruined_Nursery x352 y320": return 30;
        case "Missiles Max cho_Ruined_Fountain x576 y160": return 31;
        case "Energy Tanks Max cho_Training_Chamber x392 y72": return 32;
        case "Missiles Max cho_Training_Chamber_Access x288 y144": return 33;
        case "Power Bombs Max cho_Magma_Pool x584 y168": return 34;
        case "Missiles Max cho_Vault x192 y112": return 35;
        case "Artifact 2 mag_Warrior_Shrine x112 y64": return 36;
        case "Ice Spreader mag_Shore_Tunnel x152 y148": return 37;
        case "Energy Tanks Max mag_Transport_Tunnel_A x160 y48": return 38;
        case "Power Bombs Max mag_Fiery_Shores x576 y32": return 39;
        case "Missiles Max mag_Storage_Cavern x48 y80": return 40;
        case "Missiles Max mag_Triclops_Pit x512 y64": return 41;
        case "Artifact 8 mag_Lava_Lake_subC x274 y78": return 42;
        case "Plasma Beam mag_Plasma_Processing x192 y128": return 43;
        case "Energy Tanks Max mag_Magmoor_Workstation x568 y377": return 44;
        case "Missiles Max mag_Fiery_Shores x48 y64": return 45;
        case "Artifact 6 pha_Elite_Research x112 y96": return 46;
        case "Missiles Max pha_Elite_Research_subB x128 y32": return 47;
        case "Artifact 12 pha_Phazon_Mining_Tunnel x104 y347": return 48;
        case "Incinerator pha_Storage_Depot_A x160 y120": return 49;
        case "Missiles Max pha_Security_Access_A x192 y176": return 50;
        case "Grapple Beam pha_Storage_Depot_B x208 y139": return 51;
        case "Phazon Suit pha_Elite_Quarters x320 y352": return 52;
        case "Energy Tanks Max pha_Processing_Center_Access x72 y120": return 53;
        case "Energy Tanks Max pha_Ventilation_Shaft x152 y352": return 54;
        case "Missiles Max pha_Elite_Control_Access x224 y48": return 55;
        case "Missiles Max pha_Fungal_Hall_Access x208 y400": return 56;
        case "Missiles Max pha_Fungal_Hall_B x912 y240": return 57;
        case "Missiles Max pha_Main_Quarry x592 y48": return 58;
        case "Missiles Max pha_Metroid_Quarantine_A x512 y48": return 59;
        case "Missiles Max pha_Metroid_Quarantine_B x888 y304": return 60;
        case "Missiles Max pha_Phazon_Processing_Center x568 y632": return 61;
        case "Power Bombs Max pha_Central_Dynamo x312 y296": return 62;
        case "Artifact 3 phe_Control_Tower_subC x240 y128": return 63;
        case "Energy Tanks Max phe_Research_Lab_Aether_subB x169 y144": return 64;
        case "Missiles Max phe_Research_Lab_Aether x352 y192": return 65;
        case "Artifact 9 phe_Chozo_Ice_Temple_subD x168 y152": return 66;
        case "Wave Beam phe_Chapel_of_the_Elders_subB x144 y136": return 67;
        case "Artifact 11 phe_Storage_Cave x184 y120": return 68;
        case "Spider Ball phe_Quarantine_Cave x320 y298.67": return 69;
        case "Missiles Max phe_Quarantine_Monitor x184 y128": return 70;
        case "Spazer phe_Research_Core x160 y552": return 71;
        case "Gravity Suit phe_Gravity_Chamber x80 y96": return 72;
        case "Missiles Max phe_Gravity_Chamber_subB x56 y32": return 73;
        case "Super Missile phe_Observatory x304 y56": return 74;
        case "Energy Tanks Max phe_Ruined_Courtyard x16 y400": return 75;
        case "Energy Tanks Max phe_Transport_Access x160 y160": return 76;
        case "Missiles Max phe_Frost_Cave x296 y392": return 77;
        case "Boost Ball phe_Phendrana_Canyon_subB x144 y112": return 78;
        case "Missiles Max phe_Ice_Ruins_East x16 y32": return 79;
        case "Missiles Max phe_Ice_Ruins_East x368 y256": return 80;
        case "Missiles Max phe_Phendrana_Shorelines_subB x112 y832": return 81;
        case "Missiles Max phe_Phendrana_Shorelines_subB x544 y256": return 82;
        case "Power Bombs Max phe_Ice_Ruins_West x360 y248": return 83;
        case "Missiles Max phe_Research_Lab_Hydra_subB x376 y160": return 84;
        case "Power Bombs Max phe_Security_Cave x168 y120": return 85;
        case "Artifact 1 tal_Cipher_Site x288 y371": return 86;
        case "Artifact 7 tal_Life_Grove x488 y320": return 87;
        case "Screw Attack tal_Life_Grove x72 y344": return 88;
        case "Missiles Max tal_Life_Grove_Tunnel x304 y96": return 89;
        case "Energy Tanks Max tal_Cargo_Freight_Lift_to_Deck_Gamma x233 y124": return 90;
        case "Energy Tanks Max tal_Hydro_Access_Tunnel x576 y144": return 91;
        case "Missiles Max tal_Biohazard_Containment x265 y384": return 92;
        case "Missiles Max tal_Arbor_Chamber x144 y80": return 93;
        case "Missiles Max tal_Root_Cave x48 y208": return 94;
        case "Missiles Max tal_Transport_Tunnel_B x152 y160": return 95;
        case "Missiles Max tal_Crash_Site x616 y296": return 96;
        case "Missiles Max tal_Great_Tree_Chamber x152 y136": return 97;
        case "Space Jump Boots tal_Alcove x224 y128": return 98;
        case "Missiles Max tal_Landing_Site x800 y528": return 99;
        case "Missiles Max tal_Overgrown_Cavern x144 y128": return 100;
    }
    return -1;
}

function mw_ap_scout_ids_json()
{
    return "[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100]";
}
