from __future__ import annotations

import argparse
import ast
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ITEMS_PATH = ROOT / "apworld" / "items.py"
LOCATIONS_PATH = ROOT / "apworld" / "locations.py"
OUTPUT_PATH = ROOT / "gamemod" / "code" / "rando_scripts" / "gml_GlobalScript_mw_ap_mappings.gml"


def assigned_dict(path: Path, name: str) -> ast.Dict:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in tree.body:
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.target.id == name:
            if isinstance(node.value, ast.Dict):
                return node.value
    raise ValueError(f"{name} must be a literal dictionary in {path}")


def string_constant(node: ast.AST, description: str) -> str:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    raise ValueError(f"{description} must be a string literal")


def load_tables() -> tuple[list[str], list[str]]:
    item_table = assigned_dict(ITEMS_PATH, "ITEM_TABLE")
    item_names = [string_constant(key, "ITEM_TABLE key") for key in item_table.keys]

    location_table = assigned_dict(LOCATIONS_PATH, "LOCATION_TABLE")
    location_keys: list[str] = []
    for value in location_table.values:
        if not isinstance(value, ast.Call) or not value.args:
            raise ValueError("LOCATION_TABLE values must be LocationData calls")
        location_keys.append(string_constant(value.args[0], "LocationData location key"))

    if len(item_names) != len(set(item_names)):
        raise ValueError("ITEM_TABLE contains duplicate item names")
    if len(location_keys) != len(set(location_keys)):
        raise ValueError("LOCATION_TABLE contains duplicate game keys")
    if "Spider Ball phe_Quarantine_Cave x320 y298.67" not in location_keys:
        raise ValueError("Spider Ball's exact decimal location key is missing")
    return item_names, location_keys


def gml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render(item_names: list[str], location_keys: list[str]) -> str:
    item_lines = ",\n".join(f"        {gml_string(name)}" for name in item_names)
    location_lines = ",\n".join(f"        {gml_string(key)}" for key in location_keys)
    inverse_lines = "\n".join(
        f"        case {gml_string(key)}: return {location_id};"
        for location_id, key in enumerate(location_keys, 1)
    )
    scout_ids = json.dumps(list(range(1, len(location_keys) + 1)), separators=(",", ":"))
    return f"""// Generated by tools/generate_ap_mappings.py. Do not edit by hand.
// -- MW Changes Start

function mw_ap_item_names()
{{
    static names = [
{item_lines}
    ];
    return names;
}}

function mw_ap_item_name(item_id)
{{
    var names = mw_ap_item_names();
    if (item_id < 1 || item_id > array_length(names))
    {{
        return "";
    }}
    return names[item_id - 1];
}}

function mw_ap_location_keys()
{{
    static keys = [
{location_lines}
    ];
    return keys;
}}

function mw_ap_location_key(location_id)
{{
    var keys = mw_ap_location_keys();
    if (location_id < 1 || location_id > array_length(keys))
    {{
        return "";
    }}
    return keys[location_id - 1];
}}

function mw_ap_location_id(location_key)
{{
    switch (location_key)
    {{
{inverse_lines}
    }}
    return -1;
}}

function mw_ap_scout_ids_json()
{{
    return {gml_string(scout_ids)};
}}
// -- MW Changes End
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate GameMaker AP item/location mappings")
    parser.add_argument("--check", action="store_true", help="fail if the checked-in mapping is stale")
    args = parser.parse_args()

    item_names, location_keys = load_tables()
    rendered = render(item_names, location_keys)
    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"stale generated mapping: run {Path(__file__).name}")
        print(f"mapping is current: {len(item_names)} items, {len(location_keys)} locations")
        return 0

    OUTPUT_PATH.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"generated {OUTPUT_PATH}: {len(item_names)} items, {len(location_keys)} locations")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
